# fly.toml app configuration file generated for pt-datingapp on 2023-12-29T10:38:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pt-datingapp"
primary_region = "lax"

[build]
  image = "petertrefren/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "824444883148767"
  CloudinarySettings__CloudName = "demn5pyp3"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
